### ISSUE TITLE
assets will sometimes stop rebuilding

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#11]
every once in a while our dev server stops picking up changes. when we `rm -rf public` and restart it works again

seems to happen when we deploy or run integration tests

seems similar to the problem @charleshansen fixed recently 

we're on the newest version of pui-react-tools

**Comment by charleshansen** [comment]
I believe this is actually a bug in react starter that was fixed shortly after you forked from it. You need to make sure your server serves up development assets preferentially over production assets. Take a look at https://github.com/pivotal-cf/react-starter/blob/master/server/app.js to see the correct server setup.

**Comment by atomanyih** [comment]
oooh I misunderstood. thanks!
