### ISSUE TITLE
babel-eslint upgrade breaks .eslintrc

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#13]
seems the babel removed a rule in between versions 4 and 6, so upgrading from `pui-react-tools` `1.3.7` to `1.3.8` borks existing `.eslintrc` files

```
  1:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels  no-empty-label
```

**Comment by rdy** [comment]
Yea I saw this as well. I'll take care of this.

**Comment by rdy** [comment]
I fixed this in react-starter, repos based on this won't have this problem.
