### ISSUE TITLE
application.json scripts array prepends '/' to all scripts

### ISSUE THREAD

**Issue by aegatlin** [pivotal-cf/pui-react-tools#17]
If you want to fetch a third party resource, i.e., <script src="https...">, you cannot. It will prepend a '/', resulting in <script src="/https..." >.

**Comment by charleshansen** [comment]
Should be fixed in 1.4.4.

As a side note, it would have mostly worked it you used '/google.com/maps.js' instead of 'https://google.com/maps.js'
