### ISSUE TITLE
ability to register a loader with webpack

### ISSUE THREAD

**Issue by codeword** [pivotal-cf/pui-react-tools#18]
Based on https://github.com/pivotal-cf/pui-react-tools/blob/master/src/webpack/webpack.config.js#L24-L30 we think we've discovered this is not possible.

Currently there does not appear to be a way to add `module.loaders` to the `base` config in your `pui-react-tools.js` file since this is overridden by the `envConfig`. It looks like we could override it if we did it via `userEnvConfig` but this would mean we'd need to do add it for all environments. Even then if we could override we would be replacing all the loaders already defined in `development.js` which doesn't seem ideal.

**Comment by charleshansen** [comment]
Adding loaders is much easier in version 3
