### ISSUE TITLE
child_process

### ISSUE THREAD

**Issue by aeldaly** [pivotal-cf/pui-react-tools#21]
I'm getting this error:

ERROR in ./~/pui-react-tools/foreman/foreman.js
Module not found: Error: Cannot resolve module 'child_process' in /Users/aeldaly/Code/node_modules/pui-react-tools/foreman
 @ ./~/pui-react-tools/foreman/foreman.js 7:15-39

Thrown by simply including this line:
`const Assets = require('pui-react-tools').Assets;`

This is my pui-react-tools.js
```
module.exports = {
  webpack: {
    integration: { devtool: 'source-map' }
  }
};
```

.babelrc
```
{
  "env": {
    "development": {
      "plugins": ["react-hot-loader/babel"]
    }
  },
  "presets": ["es2015-loose", "react", "stage-0"],
  "plugins": [
    "transform-object-assign",
    "transform-react-display-name"
  ]
}
```

config/application.json
```
{
  "globalNamespace": "namesapce",
  "title": "Welcome!",
  "scripts": [
    "application.js"
  ],
  "stylesheets": [
    "application.css"
  ],
  "useRevManifest": false
}
```

config/env.json
`[]`

**Comment by charleshansen** [comment]
Are you requiring `pui-react-tools` in client-side javascript? Webpack will throw that error if you do.

Requiring `pui-react-tools` will require `foreman.js`, which requires `child_process`. This code is meant to be run in node (at compile time), where child_process should be available. This means you should require it in a file that is ultimately required by your `gulpfile.js` and not required by your `application.js`

**Comment by rdy** [comment]
it looks like this might be caused by a newer version of node, i'm not sure of the cause but it looks like a printed warning rather than a real one. it might have been introduced as part of node 7
