### ISSUE TITLE
adding webpack plugins is hard

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#22]
similar to #18

to add plugins we have to do this:

```js
const {plugins: basePlugins} = require('pui-react-tools/webpack/base');
const {plugins: testPlugins} = require('pui-react-tools/webpack/test');
const {plugins: devPlugins} = require('pui-react-tools/webpack/development');
const {plugins: prodPlugins} = require('pui-react-tools/webpack/production');

const webpack = require('webpack');

const myPlugin = new webpack.DefinePlugin({
  ENABLE_DEBUG_LOGGING: JSON.stringify(config.enableDebugLogging)
});
module.exports = {
  webpack: {
    base: {
      plugins: [
        ...basePlugins,
        myPlugin
      ]
    },
    test: {
      plugins: [
        ...testPlugins,
        myPlugin
      ]
    },
    development: {
      plugins: [
        ...devPlugins,
        myPlugin
      ]
    },
    production: {
      plugins: [
        ...prodPlugins,
        myPlugin
      ]
    },
    integration: { devtool: 'source-map' }
  }
};
```

I know yall probably already know this, but here it is

**Comment by charleshansen** [comment]
Agreed. Always looking for suggestions on this one :)

**Comment by atomanyih** [comment]
I guess to start, the above method could be documented so that people don't keep having to look through the source to figure it out.

I have other thoughts that I'll write out later

**Comment by atomanyih** [comment]
Thoughts:

Goals of `pui-react-tools`
1) make it easy to start a project without knowing webpack, gulp, babel etc  
2) provide sane defaults  

We opted to hide away webpack and gulp, but as a result it's harder to customize the build. In particular, it's harder to accomplish some common use cases. I've needed to add loaders or plugins on almost every project, which is easy with webpack, but hard with pui-react-tools (or I have to rely on knowledge of pui-react-tools' internals). 

Possible solutions

a) Further hide underlying tools by adding support for more use cases

Provide out of the box support for adding loaders and plugins. Do some research with pivots that have used pui-react-tools on projects to see what people needed but didn't have. Look at other libraries trying to accomplish the same thing. 

b) Hide webpack less

Let pui-react-tools generate barebones starter gulp tasks and whatever like `create-react-app` or `rails init` does but with the libraries that we like to use at pivotal (Jasmine, etc). Roll back the things that make the assets task easy to use but hard to customize.

My preference is for b, especially since we're sending clients home with projects dependent on pui-react-tools.

We can't really predict what clients will need a year after they disengage; they might want to inline certain font filetypes to speed up rendering; they might want to put some assets on a cdn. These are things that are hard or non-obvious with pui-react-tools and they can't look for answers on stackoverflow. At that point they're tied to a tool they don't know how to use and have to either go from 0 to 100 on webpack or grep through the source to figure out how to bend it to fit their needs.

We can write more documentation and build more tools but between dataviz, client projects, and all the other things we have to work on it doesn't seem like there is bandwidth to create a tool that accommodates diverse project needs, and it doesn't have community support to be self-sustaining.

If we generate just what's needed to start a project it's a win-win: we don't have to support projects long-term as webpack, babel, or other libraries update; clients can incrementally customize to fit project needs as they learn webpack. Less work for us, more long-term freedom for them.

Anyway, I know that the webpack config thing in particular is a hard problem, but after a number of projects with and without `pui-react-tools` I feel like we should re-evaluate whether it's a good idea to use with clients

**Comment by charleshansen** [comment]
I am also a fan of the 'hide webpack less' strategy. Webpack is more popular now and hopefully less of an issue to get developers to use it. I'm not always a big fan of generators, since they become out of date very quickly and can't be upgraded, but that might be the way to go. I think pui-react-tools has stabilized enough to make this a possible plan. We should discuss more...

**Comment by charleshansen** [comment]
version 3 is finally out, we are now going with option b
