### ISSUE TITLE
loading images through webpack

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#25]
for posterity:

 @ddzoan and I were trying to load images through webpack like so:

```jsx
<img src={require('../../images/my-image.png')}/>
```

this worked fine in dev through `url-loader` but in prod `file-loader` was giving the wrong source url: `src="current/path/my-image.png"` as opposed to `src="/my-image.png"`

to make it work we had to tell `file-loader` to use `/` as the `publicPath`

`pui-react-tools.js`:
```js
module.exports = {
  webpack: {
    base: {
      output: {
        filename: '[name].js',
        chunkFilename: '[id].js',
        publicPath: '/'
      }
    }
  }
};
```

Then we noticed both the `assets` task and `file-loader` were copying images to `public/images` and `public/`, respectively. To fix this, @charleshansen told us we needed to turn off the image copying part of the assets task:

`tasks/react_tools.js`:
```js
Assets.install({
  assets: {
    sass: false,
    html: false,
    images: false
  },
  useAssetsServer: false
});
```

**Comment by charleshansen** [comment]
this part of the assets task is totally different in version 3
