### ISSUE TITLE
required stylesheets are always used in production

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#26]
we have a test stylesheet that disables animations in test:

```js
if (window.location.href.match(/test_mode=true/)) {
  require('./stylesheets/test.scss');
}
```

because of the way css is extracted in the production, it's always bundled as part of `application.css`

this is a kind of sketch use case so I don't think it's really an issue, but ![the more you know](http://i2.kym-cdn.com/photos/images/original/000/620/434/f9e.gif)

**Comment by charleshansen** [comment]
Agreed, it does do that. You can probably divert it to a new css file by setting your own loaders (vaguely like `require('!!(extract-text-stuff)!./stylesheets/test.scss')`), then you can add an extra stylesheet in your `test.json`. It is moderately hacky, but could work

**Comment by charleshansen** [comment]
You control your own webpack config in version 3, so you can turn this off by adding an exclude to your sass loader
