### ISSUE TITLE
Build folder outside of working folder

### ISSUE THREAD

**Issue by BoykoAlex** [pivotal-cf/pui-react-tools#29]
I have specified build folder being something like `../src/main/resources/public`. Now I have `asset-cleanup` task failing to delete resources outside of working folder. This is unless `force` flag is specified. Where is the `force` flag should be specified? Any advice on how to do this properly? I didn't expect temporary files being used for tests being in the build folder? Perhaps I'm better off building in the default folder `public` and then copying the result of the build in `../src/main/resources/public`. If that makes sense, how would you do that properly?

**Comment by BoykoAlex** [comment]
Never mind. Sounds like it's best to have a build folder inside the project folder. I can work around this.

**Comment by charleshansen** [comment]
Yeah, I tried to pull files from outside once. I don't fully understand why, but it wasn't possible. I think webpack can't pull in files that are above it's own root directory. 
If pui-react-tools is setup correctly, you shouldn't have any temporary test files in your build directory, they should be ephemeral, piped directly into gulp-jasmine-browser. Feel free to open a new issue if your workaround isn't great.
