### ISSUE TITLE
Impossible to disable linter fixing

### ISSUE THREAD

**Issue by jberney** [pivotal-cf/pui-react-tools#35]
There is a bug in this line in src/lint/lint.js:
`const {FIX: fix = true} = process.env;`

It is impossible to provide a value for process.env.FIX such that the `fix` variable becomes falsy. Even if you set it to "false", you get "false" the string, which is truthy.

The line should probably become something like this:
`const fix = JSON.parse(process.env.FIX || 'false');`

**Comment by charleshansen** [comment]
Added a fix in 3d79d424779faaadfa67e07cc2fadfc0d7187a8a, had some minor difficulty publishing it, so it isn't in yet.

**Comment by charleshansen** [comment]
published in 2.0.6
