### ISSUE TITLE
Upgrading to 5.0.0 makes `yarn gulp spec-app` hang indefinitely

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal-cf/pui-react-tools#39]
When we upgrade pui-react-tools from 4.0.1 to 5.0.0, `yarn gulp spec-app` starts to hang indefinitely. If we run the tests in the browser (i.e. go to localhost:8888 after running `yarn jasmine`) they all run just fine. It's worth noting that the command still hangs if we comment out all of the tests and all of the code, so it appears not to be a problem with a malformed test.

```
$ ./scripts/yarn test
yarn run v1.7.0
$ gulp spec-app
[16:42:10] Failed to load external module @babel/register
[16:42:10] Requiring external module babel-register
[16:42:11] Using gulpfile ~/workspace/djavos/frontend/gulpfile.babel.js
[16:42:11] Starting 'spec-app'...
[16:42:11] Starting 'spec-app-run'...
[16:42:11] Starting 'jasmine-detect'...
[16:42:11] Finished 'jasmine-detect' after 43 ms
[16:42:11] Starting 'specAppRun'...
[16:42:11] Jasmine server listening on port 8888
# It hangs here forever and ever until you ctrl-c
^C 
undefined specs, 0 failures
Finished in NaN seconds

[16:42:39] Finished 'specAppRun' after 29 s
[16:42:39] Finished 'spec-app-run' after 29 s
[16:42:39] Finished 'spec-app' after 29 s
```

Relevant excerpts from our `gulpfile.babel.js`:
```
headlessServerOptions: {
    includeStackTrace: true,
    random: true,
    isVerbose: true,
    port: 8888,
    driver: 'chrome',
  },
  headlessSpecRunnerOptions: {profile: true},
```

For context, we are using the following node packages
```
"pivotal-ui": "^16.0.0",
"react": "^16.3.1",
"gulp": "^4.0.0",
"gulp-jasmine-browser": "^3.0.1",
"webpack": "^4.11.1"
"pivotal-js-react-test-helpers": "^0.1.0",
```

Also here's the output of `yarn versions`
```
yarn versions v1.7.0
{ yarn: '1.7.0',
  djavos: '0.1.0',
  http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
✨  Done in 0.06s.
```

Let me know if there is any more information we can provide to help y'all diagnose this.

**Comment by jberney** [comment]
We were able to reproduce this in a fresh app created by `create-react-app`. Our fix was composed of the following:
1. In the Chrome driver, when there is an `error` or `pageerror` event during headless testing, we catch that error, report it in the user's console, and end the test run. We should no longer hang when there is a browser error of any kind.
1. We found that there was a breaking change from Jasmine 2.x -> 3.x that was causing the browser to error out. We updated the Chrome driver to account for this change, so now tests should be able to pass as a result.

We've released these fixes in [5.0.1](https://www.npmjs.com/package/pui-react-tools/v/5.0.1).
