### ISSUE TITLE
assets should be able to copy arbitrary files

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#4]
We're pulling in font-awesome now and we want to throw the file into the normal assets pipeline

I was also thinking about the way we do configuration. It might be kind of cool if instead of defining stuff in json we could do this:

``` js
require('pui-react-tools').Assets.install({
  title: "Spruce",
  scripts: [
    "application.js"
  ],
  stylesheets: [
    "application.css"
  ]
});
```

and for us it would be

``` js
require('pui-react-tools').Assets.install({
  title: "Spruce",
  scripts: [
    "application.js"
  ],
  stylesheets: [
    "application.css",
    {src: 'node_modules/font-awesome/css/font-awesome.min.css', dest: "font-awesome.min.css"}
  ]
});
```

I haven't thought the last part out totally, but we'll do a PR to copy assets when we fix our production deploy script

**Comment by charleshansen** [comment]
Pretty sure this was addressed in person, but closing for version 3
